### ISSUE TITLE
Suggestion: add an option to change date format

### ISSUE THREAD

**Issue by correctstrawberry** [Arthur-Milchior/anki-enhance-main-window#12]
The window that is opened when a deck is selected has a "Done on" section that displays an approximate date for the deck's completion. The date format is DD.MM.YY. Would it be possible to make changing this easier, perhaps in the "other options" section? I looked through the code but was unable to find where this is coded. For example, maybe a line like `"date format" : "YYYY-MM-DD",` would make the date look like 2018-09-27 rather than 27.09.2018.

**Comment by Arthur-Milchior** [comment]
Hello,

I beg your pardon, I really do not understand what you are asking for. 
«the window», which one ? May be, you can take a screen shot, it will be easier to explain the trouble.
«Done on», I can't find this text anywhere in anki code, nor in my addon, so I really don't understand what your are looking for.
Anyway, if the problem is not on the window with the list of deck, then it's not related to this add-on. Which does not mean I can't help you.

Regards,
Arthur

**Comment by correctstrawberry** [comment]
@Arthur-Milchior Whoops, I was looking at the wrong addon. Sorry about that. Thanks for your addon by the way, it's very helpful.
