### ISSUE TITLE
The new "cards" column generates an error in Anki other than the English language

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#17]
The new "cards" column generates an error in Anki other than the English language. I believe that the source code at some point is not "translating" the term. The language of my Anki is pt-br.

**All other columns work normally.**

**Column:**
`(_("cards"), _("Total"),"black", _("Number of cards in the deck"), "absolute", "subdeck"),`

![image](https://user-images.githubusercontent.com/42243532/47603361-628b1e00-d9c1-11e8-8625-2b9607502a54.png)

Removing only the "_" from the term below, resolved. 

`(("cards"), _("Total"),"black", _("Number of cards in the deck"), "absolute", "subdeck"),`

Could you correct so you do not have to do this?
I did not have to make that change for the others. Just this.

**Comment by Arthur-Milchior** [comment]
Corrected. Yeah, you are totaly right in your correctiong. 
For your information, in anki, _("things") Means «translate "things" in the current language». Thus it was translating «cards». However, it should note, since this text is not supposed to be displayed to the user, but used by anki to figure out what it should display

**Comment by cjdduarte** [comment]
Adjusted. Thank you.
