### ISSUE TITLE
Accents "pt-br" does not work on Anki 2.0

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#20]
Hi, I remember that we fixed this in Anki 2.1 and it works correctly.

But in version 2.0 I translated the texts of your addon and in this version, it does not work, an error occurs.
Example.

![image](https://user-images.githubusercontent.com/42243532/49027446-5690a880-f187-11e8-85c1-1600cb5d0076.png)

```
Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\cjddu\AppData\Roaming\Anki2\addons\Enhance_main_window.py", line 64, in <module>
    (("new"),              	_("Novos"),"blue",                      _("Cartões novos que você verá hoje")        +"<br/>"+_("(o anki chama de novos)"), "absolute", "subdeck"),
  File "gettext.py", line 479, in ugettext
  File "gettext.py", line 480, in ugettext
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```

We have an active community here in Brazil, some still use Anki 2.0

**Comment by Arthur-Milchior** [comment]
I beg your pardon. I mostly work on add-on I use myself. I don't use 2.0, so I don't intend to correct bugs on 2.0. At least, not unless I'm paid for it. 
You may want to delete the _ before the opening parenthesis. _(FOO) means "check in the database whether you know the translation of foo in the local language. In this case, use the translation, otherwise keep the current version." Since you write the translation directly in the code, _ becomes useless.

**Comment by cjdduarte** [comment]
It worked. I also use version 2.1, but it was requested by friends from version 2.0.

Thank you.
