### ISSUE TITLE
Error when expanding subdecks

### ISSUE THREAD

**Issue by chkmte** [Arthur-Milchior/anki-enhance-main-window#22]
Clicking the + or - button to expand or collapse a deck's subdecks generates an error. Is resolved when I disable this add-on. Only started with a recent update.

![image](https://user-images.githubusercontent.com/45411294/49124975-5f1ed700-f28c-11e8-8de3-700185a69fcc.png)

![error](https://user-images.githubusercontent.com/45411294/49124994-6cd45c80-f28c-11e8-9462-6e92ebf53f77.JPG)

**Comment by Arthur-Milchior** [comment]
Hi,

Thank you for reporting the error.
I just downloaded the add-on again, to test it. It works fine.
I assume you pasted the whole error message ? Because I must admit that, right now, I have no clue what's wrong. 
I'm on ubuntu, so it may be OS related error.
I use the current version of anki, I can easily imagine that it's an error related to a change between current version and beta. I honestly never figured out how to install code anki from source, so I can't really test this hypothesis.

I'll try to see what the «onclick handler» line refer to. May be it'll help. But debugging without testing is hard

**Comment by Arthur-Milchior** [comment]
I tried to solve the problem. Can you let me know if current version works better please ?

**Comment by chkmte** [comment]
The current version seems to have resolved the problem. Thank you very much for your prompt response!

For future reference you can download the beta versions from the following link.
https://apps.ankiweb.net/downloads/beta/

The below link goes over the main changes in the beta versions, and has links for the downloads and reporting problems.
https://apps.ankiweb.net/docs/beta.html

**Comment by Arthur-Milchior** [comment]
Great.
Thank you a lot. I'm quite happy that to learn about a beta-related problem before it becomes the current version.
