### ISSUE TITLE
Small graphical issue

### ISSUE THREAD

**Issue by sandersantema** [Arthur-Milchior/anki-enhance-main-window#23]
I believe it shouldn't be possible to scrol to the right. It is not really important but I think it would look better if the scrollbar wasn't visible. 

<img width="1280" alt="schermafbeelding 2018-11-29 om 16 29 31" src="https://user-images.githubusercontent.com/21057514/49232564-7c6eb500-f3f4-11e8-94d0-1197d4fdfc11.png">

**Comment by Arthur-Milchior** [comment]
I do understand your request. I won't solve it. 
This add-on deals with HTML only, and its formatting. The scrollbar is not a part of the HTML.
I guess that CSS could be used to deactive the scrollbar when it's not used. But doing good CSS is a difficult task, I don't think I want to ever deal with it if I can avoid.
It is also possible that the scrollbar is not in the HTML interpreter, but is generated by QT. I may eventually one day take a serious look at QT. It's not planned right now either. 

To be even more honest, I first write the add-ons because I believe they help me. This is not a problem for me. So I'm not really motivated in fixing it. On the other hand, it is theoretically possible that the last bug you reported would also have happened when I use anki, so I wanted to fix it as soon as possible.

**Comment by cjdduarte** [comment]
I solved this problem using the "Zoom addon" and decreased the screen

**Comment by cjdduarte** [comment]
Another alternative that may work is to decrease the spacing between the columns. I prefer the value of 5 instead of 15.
![image](https://user-images.githubusercontent.com/42243532/49865719-d99f3900-fdec-11e8-888f-01d4923e493c.png)

Since it is now possible to use the configuration of the addon by Anki, would it be possible to implement the parameterization of that number?

**Comment by Arthur-Milchior** [comment]
it should present no problem at all. I won't do it right now, but I'll be sure to do allow css configuration on my next update.

**Comment by cjdduarte** [comment]
OK.
