### ISSUE TITLE
Addon is not reading the description of the columns of the configuration module

### ISSUE THREAD

**Issue by cjdduarte** [Arthur-Milchior/anki-enhance-main-window#26]
Addon is not reading the description of the columns of the configuration module.
The addon is ignoring the JSON and reading the translation of the enhancedMain.py file.

Example

Text that I translated into the "**new**" column:

![image](https://user-images.githubusercontent.com/42243532/49864402-85df2080-fde9-11e8-805d-14dbaaafb476.png)

EnhancedMain.py text:

![image](https://user-images.githubusercontent.com/42243532/49864503-c343ae00-fde9-11e8-97b9-b9fbc2dc8cf3.png)

As is being shown on Anki: The text of enhancedMain.py
![image](https://user-images.githubusercontent.com/42243532/49864634-0dc52a80-fdea-11e8-8ac1-1cef81d453f3.png)

**Comment by Arthur-Milchior** [comment]
As explained in https://github.com/Arthur-Milchior/anki-enhance-main-window/blob/master/config.md (the file shown to you by anki's add-on manager), the description is not used by the add-on. It's here because the user (you), need to have a short description of the column in order to edit the configuration.

What you are looking for is «overlay», which you can edit to put the text that you want

**Comment by cjdduarte** [comment]
OK. Thanks for explanation.
