### ISSUE TITLE
2.1.7 error *bug*

### ISSUE THREAD

**Issue by RealMedicMD** [Arthur-Milchior/anki-enhance-main-window#29]
![image](https://user-images.githubusercontent.com/43578847/50283921-ff47c600-041c-11e9-8efd-16696e8e2a2d.png)

occurs only when enhance main window is on, after upgrading to anki 2.1.7. specifically occurs when expanding or collapsing decks.

edit: more detail

**Comment by Arthur-Milchior** [comment]
Did you try upgrading the add-on. Normally it is already fixed thanks to a
user of the beta version of anki.

Le jeu. 20 déc. 2018 à 13:03, RealMedicMD <notifications@github.com> a
écrit :

**Comment by RealMedicMD** [comment]
Yes it is the latest version from the Anki Addons page

**Comment by Arthur-Milchior** [comment]
I just installed anki 2.1.7. I tested. I have no problem.
I have no idea what the problem could be.
I'm sorry to have to ask this again. Did you open the add-on manager (tools, add-ans), clicked on «check for updates» and finally accepted the update.
Because you have exactly the same error message than #22, and they told me that the error was resolved.
