### ISSUE TITLE
issue since the last update

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Arthur-Milchior/anki-enhance-main-window#45]
Hi,
I have been having an issue on anki 2.1.6 (I then updated to 2.1.8 to no avail) just after updating your addon. I have this at startup : 

```
Anki 2.1.8 (71e0c880) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Linux
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt/webview.py", line 300, in handler
  File "aqt/deckbrowser.py", line 90, in __renderPage
  File "/home/USER/.local/share/Anki2/addons21/877182321/node.py", line 547, in renderDeckTree
    buf = f"""<style>{css}</style>{start_header}{deck_header}"""
<class 'NameError'>: name 'css' is not defined
```

I also removed and readded your addon.
I don't know what version of the addon I was using in the past but it might be a few months old.

What can I do to help you ?

I am on ubuntu 18.04

**Comment by Arthur-Milchior** [comment]
Excuses me, what do you mean by «readded» ?
I totally fail to understand how this bug can occur. 

I redownloaded my addon, but this bug don't appear. No one else reported this bug. So I assume that something maybe went wrong on your cide. But honestly, I can't even image what would cause this bug. It certainly does not seems to be interaction with any other add-on.

Is there anything unusual with your installation of anki ?
Can you may be zip the folder /home/glume/.local/share/Anki2/addons21/877182321/ and send it to me, so I can at least check whether you have the correct files

**Comment by thiswillbeyourgithub** [comment]
By "readded" I meant that I removed your addon by clicking "delete" in the addon manager window and then reinstalled it using the "get-addon" button.

I don't think there is anything unusual with my installation of anki. I know I changed a few things in the config file (from the addon manager window) to display only the columns I needed but that shouldn't have anthing to do with that issue.

Here's the file : 
[archive.tar.gz](https://github.com/Arthur-Milchior/anki-enhance-main-window/files/2879335/archive.tar.gz)

**Comment by Arthur-Milchior** [comment]
I just checked, this archive contains the correct version of the file. The only difference being in meta.json, since you disabled the add-on. 
Here, you have the original configuration (probably due to the fact that you deleted and installed again)
For everything else, we have the same files.

So I really fail to understand what could be going wrong. 
Would you please suspend all add-on (for example by moving them out of the add-on folder), and check if, when they are no other add-on, this add-on works ? So I'll know whether it's a problem of compatibility with another add-on (I have no clue how this could be the case. But I don't understand anything about this bug anyway)
If this add-on works when there is no other add-on, then I'll ask to test adding back add-ons, one by one (or by dichotomy, if you know what it is), to find the add-on creating the problem.

Sorry to ask you to take time for my add-on, but I don't see what else to do

**Comment by thiswillbeyourgithub** [comment]
I manually disabled all of them except yours using the addon manager window then restarted anki and it didn't change a thing :/

> Sorry to ask you to take time for my add-on, but I don't see what else to do

You definitely should ask me to take time for your addon ! It's super great and I love it, be proud of your work :)

**Comment by Arthur-Milchior** [comment]
I just asked for help on https://www.reddit.com/r/Anki/comments/asg4ka/better_python_developers_wanted_for_an/ because honestly I'm totally lost

**Comment by thiswillbeyourgithub** [comment]
Thanks !

Please don't beat yourself, your addon is a great addition to anki and you really helped this community, who cares if you are actually a developper or just a tinkerer :*

I myself know a bit of python but have not yet reached the level to make addons so you have all my respect :)

**Comment by thiswillbeyourgithub** [comment]
Oh by the way, maybe I should try some older versions of your plugin to test. Do you know how I can get them ? It doesn't seem to me like you used the "release" function of github to edit your code.

**Comment by Arthur-Milchior** [comment]
I don't even know functionality release. And I absolutly didn't keep track of which version was released. 
However, usually, the repo is a copy of what is in my add-on folder. Which means that if you see a version which has not been changed during many days, it must be stable. It may have bug when you change the config file (hopefully, there are no such bug anymore, but there used do be before I did a big rewrite of the add-on). But the version with default config file should be ok

**Comment by Arthur-Milchior** [comment]
There is actually a reason why I care about this bug. It means that there is something I don't understand about python. 
There is plenty of things I actually don't know about python, and I doubt most python coder know everything. But if it's something I use in my code, I really would like to understand it. And not make the same mistake again.

**Comment by Arthur-Milchior** [comment]
Can you please try current version of the code. I doubt it corrects the error. But I'd like to know what will be the new error message.

**Comment by thiswillbeyourgithub** [comment]
The functionnality release is a part of github FIY :)

Will do right now

**Comment by thiswillbeyourgithub** [comment]
I erased everything inside your addon's folder and cloned the repo in there.

The error is as follow : 
```

**Comment by thiswillbeyourgithub** [comment]
Maybe something is wrong with my python library ? Do you know which one I should try to reinstall ?

**Comment by Arthur-Milchior** [comment]
As far as I understand anki, it comes with its own version of Python. I guess it's something like a virtual env. I don't really understand this yet. Which is kind of frustrating, because there are some librarys I may want to use, but can't unless I package them myself in the add-ons.
Anyway, it means that changing python on your system shouldn't change anything about the bug. Unless you run anki from code and not from the anki installer.

The change I just did is that, instead of saying «import everything from file html.py» instead I ask «import the following variables and functions». And it states that the variable css is missing. Which is strange, because it certainly is present in the actual code. Maybe it import another file than html.py, but I don't know enough about python to know why it would do that, and I don't even know how to test it.

**Comment by thiswillbeyourgithub** [comment]
Personnaly I know python PROGRAMMING but nothing much on envs, programs with different files etc

Maybe I could try to load css or libs from the anki's console to see where it gets us ? I don't know the commands though :p

**Comment by Arthur-Milchior** [comment]
It wouldn't work. Because 
```from .html import css```
works on every system but yours because html.py is in the same package (i.e. folder). However, the debug console is loaded from anki's folder. And I don't know how to get information from add-ons from the debugger. Furthermore, the add-on is probably not even loaded in anki's list of add-on since there was an exception

**Comment by Arthur-Milchior** [comment]
Can you please try again ? I would kind of hate if this solution works, but it is possible that it indeed works.

**Comment by thiswillbeyourgithub** [comment]
What do you want me to try again ?


Also, here's the output from glutanimate's command on reddit : 

![screenshot from 2019-02-20 10-45-38](https://user-images.githubusercontent.com/26625900/53082358-9819c100-34f4-11e9-831c-a3204f93df2a.png)

**Comment by cjdduarte** [comment]
> What do you want me to try again ?
> 
> Also, here's the output from glutanimate's command on reddit :
> 
> ```
> >>> import importlib
> ... html = importlib.import_module(".html", "877182321")
> ... pp(html.css)
> Traceback (most recent call last):
>   File "aqt/main.py", line 1213, in onDebugRet
>   File "<string>", line 3, in <module>
> AttributeError: module '877182321.html' has no attribute 'css'
> ```

What is your linux version?
I both Windows and Mint 19 and I have no problems.

**Comment by Arthur-Milchior** [comment]
I want you to try again downloading the version on github and testing it. I
made a small change that I'd want to test

**Comment by glutanimate** [comment]
@thiswillbeyourgithub Huh, that's weird. So the `html` module within the package actually *is* getting loaded. It just can't find `css` for some reason.

Arthur's update should hopefully work, but if it doesn't: It would be interesting to see your output for the following debug commands

    import importlib
    html = importlib.import_module(".html", "877182321")
    pp(dir(html))

This will list all the members of the html module and should give us a hint as to what's happening.

**Comment by thiswillbeyourgithub** [comment]
>linux version
``uname -a`
`Linux T480s 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

will do right away and edit this comment

**Comment by thiswillbeyourgithub** [comment]
@glutanimate here's the output

```
>>> import importlib
... html = importlib.import_module(".html", "877182321")
... pp(dir(html))
['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_charref',
 '_html5',
 '_invalid_charrefs',
 '_invalid_codepoints',
 '_re',
 '_replace_charref',
 'escape',
 'unescape']
```


the new version online is working

**Comment by glutanimate** [comment]
Thanks! So we can scratch my previous remark. Seems like it actually is a name conflict with Python's html module, as initially thought. Also explains why the new version fixed things. Why this would appear despite the relative import, and why this would be limited to your system I have no idea. We might need a Python guru to solve this mystery :)

**Comment by Arthur-Milchior** [comment]
Since it works, I close the issue.
I actually and sincerly hate that I don't understand what went wrong. I guess for the foreseeable future, I'll try to ensure that my file name are distinct from python's module. 
I'll upload this version online, so you can use ankiweb's version, and get new update automatically

**Comment by thiswillbeyourgithub** [comment]
You guys are incredible ! Thanks a lot for the quick help and solving this :)

**Comment by glutanimate** [comment]
@thiswillbeyourgithub I'm not sure if you will get this message, but if you do: It seems like the issue you were experiencing here a few months ago has now resurfaced in other add-ons also. From what I can tell it seems like a general issue with Anki.

If you are up for some bug-hunting, I would very much appreciate your help with tracking this down. I took the liberty of writing a quick proof-of-concept add-on that's meant to both make the bug reproducible and also provide as with some direly-needed debug information. If you could contribute to that it would be very helpful.

For more info on the current state of our investigation and instructions on installing the bug testing add-on please see here: https://github.com/glutanimate/review-heatmap/issues/43#issuecomment-506912615

Thanks a lot in advance!

**Comment by thiswillbeyourgithub** [comment]
Hi,
I will be busy in the next week but I would be honored to give a hand :)
I will read the linked page in the next days or so.

(I hope my coffe was good :) !)
