### ISSUE TITLE
Large deck causes blank decklist

### ISSUE THREAD

**Issue by AnnanFay** [Arthur-Milchior/anki-enhance-main-window#56]
On Anki 2.1 Windows 10 adding [this large deck](https://ankiweb.net/shared/info/940918845) to Anki causes the decks list to become completely blank.

I created a new profile with only this add-on enabled and only this deck.

Blank screen: 
![image](https://user-images.githubusercontent.com/766048/58135796-b42c1c00-7c23-11e9-82e8-2406b4b033c8.png)

It's worth noting the above deck has a *stupid* amount of sub decks - about ~4 *PAGES*. First page:
![image](https://user-images.githubusercontent.com/766048/58135863-f190a980-7c23-11e9-9206-f4081ad145b2.png)

Still, might be worth having an error message saying: "Please disable Enhance main window or reduce the number of decks"

**Comment by Arthur-Milchior** [comment]
Actually, you're not the first one to have this problem. I can't explain why it occurs, but I doubt it's related to the number of deck. I should note that I literally have more than 200 decks, so I would have noticed if it was slow or not appearing.

Can you please tell me which (sub)version of anki you have ? I can't garantee it's compatible with old version, since I keep my anki up to date.
One solution would be to export your collection, create a new profile and import the collection. It seems to have worked in the past. I don't make promise

**Comment by lovac42** [comment]
Just to add a note... It only happens when you have all the subdecks expanded and exceed a certain count. It crashes if you are expanding a subdeck or it causes a blank screen at boot time. But it only affects QWebEngine, after porting this back to 2.0, I did not experience this problem. So on 2.1, if you only expand one subdeck at a time, you will not encounter this error.

**Comment by Arthur-Milchior** [comment]
How do you know that it only affects QWebEngine ?
I'm still not confortable with PyQT, or with QT, so I'd gladly have help to learn how to debug those components.

**Comment by Arthur-Milchior** [comment]
Or, let's say, even having a code which would detect when the deck browser is blank would be great

**Comment by lovac42** [comment]
I'm on windows with no IDE, so I just do it the old fashion way: ```print()```. But I tracked it down to somewhere around ```renderDeckTree```.

>How do you know that it only affects QWebEngine ?
Well I was porting this addon to CCBC which uses QtWebkit. And it didn't have this bug.
https://github.com/lovac42/CCBC

**Comment by lovac42** [comment]
Found it "QWebEngine Not rendering large html pages, fixed in Qt 5.9.2". I just tested this truncating tooltips info and it loads fine.

https://bugreports.qt.io/browse/QTBUG-59369?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&showAll=true

**Comment by AnnanFay** [comment]
The version I had the bug on was
```
Version 2.1.12 (eef86bf3)
Qt 5.12.1 PyQt 5.11.3
```

**Comment by Arthur-Milchior** [comment]
Thank you @lovac42 for the help. I fear that, given this bug report, there is nothing I could do about it. clearly, debugging PyQt is far outside of what I could do. 

@AnnanFay Did you try what I suggested ? creating a new collection and importing the old one ? I mean, I'm not sure it would work, but I guess it's worth a try.

**Comment by AnnanFay** [comment]
@Arthur-Milchior Sorry, I ended up just abandoning the issue. I ended up finding a different deck with less sub-decks which works.

**Comment by Arthur-Milchior** [comment]
No trouble. I'm just going to close the bug report in this case, until someone else have the same problem. I'm happy to learn that it works for you.
