### ISSUE TITLE
Header captions take too much space

### ISSUE THREAD

**Issue by M-Azuma** [Arthur-Milchior/anki-enhance-main-window#75]
Hi. I am new to this plugin. I find header names too long and take too much space vertically, mainly that `now later today other day`. How to solve it? 

### Normal
![image](https://user-images.githubusercontent.com/3676278/70286734-4cc46b00-1807-11ea-87f0-3567f198950f.png)

### Maximized
![image](https://user-images.githubusercontent.com/3676278/70286752-5a79f080-1807-11ea-81be-cc5e94c934ae.png)

**Comment by Arthur-Milchior** [comment]
I never tested them with translation (to be precise I use anki translation when available and default to english otherwise)
Thank you for the screenshot, it makes the problem quite easier to understand.
You can edit the configuration of the add-on (in the add-on manager). You want to change the value of the "header" of each colum. Each time you see 
`"header": null`
replace it by 
`"header": "My header"`
where "my header" is what you want your header to be.

You can recognize each columns by their name as long as you understand english.

**Comment by M-Azuma** [comment]
Thank you for your quick reply. I have managed to change them. Now it's
fine.

2019年12月6日(金) 16:05 Arthur Milchior <notifications@github.com>:

**Comment by Arthur-Milchior** [comment]
You're welcome. I close the issue then.
Please, think about tipping
