### ISSUE TITLE
Option to hide parent deck info even if child shown

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Arthur-Milchior/anki-enhance-main-window#87]
Hi!

Since switching to the V2 scheduler, anki doesn' seem to t take into account subdeck limitations when selecting the parent deck.

This is annoying to me because it makes tons of menacing 1000+ reviews gauge appear when folding down some subdecks (when I hit the daily limit of a subdeck but it still contains reviews for example).

Do you think you could consider adding an option to hide parent decks info entirely? Hence to see the numbers I would have to go all the way down the subdeck, which takes into considerations only the subdeck configuration.

Thanks a lot and good luck on your next job  :)

**Comment by Arthur-Milchior** [comment]
Done. Please look at "hide values of parent decks"

**Comment by thiswillbeyourgithub** [comment]
Oh my god, it's really sad to see you go to your new job :)

Your next coffee is on me!
 
Thank you for everything.

**Comment by Arthur-Milchior** [comment]
To be perfectly honest:
1. I am a tea person, not a coffee one. I already have a full cup of genmaicha near me.
2. while I do sincerely appreciate those tips, they were not enough to pay a rent. I personally am extremely happy that I know can tell that I'll make more in a week than what I did since I started contributing to the anki ecosystem. Even if I must admit that it is possible that it only means that I'm bad at selling myself and negociating, since Glutanimate proves that it's possible to make more
