### ISSUE TITLE
Compatibility with Anki 2.1.28

### ISSUE THREAD

**Issue by hugomarins** [Arthur-Milchior/anki-enhance-main-window#90]
Dear @Arthur-Milchior ,

I know you are very busy lately, but I decided to tell you personally that many people like me cannot live without this add-on anymore. It is a perfect and thorough X-Ray of all important issues for managing large and complex card database.

I know 2.1.28 is still a beta, but I want to beg you to update this add-on, if you can, when the stable version is released.

I really have no words to thank you for your work helping Damien and developing your add-ons, especially this one. 

May God be pleased to help and bless you and make your ways prosper.

**Comment by Arthur-Milchior** [comment]
Hi,

I've been running anki on Master for months at least. I sadly now very well that it does not work anymore. Actually, I believe it is indicated on the add-on page, so that user simply see the add-on not working instead of seeing error message)

However, Anki is changing so quickly right now that I can't port the add-on immediately without fearing that it will break in the next alpha. If people are willing to pay for it, my housemate takes free lance commission and I can help them in order to understand the complex code behind anki, but I don't believe anyone right now can create an add-on and ensure it'll still work in next version of anki.

Note that I'm not complaining here, this is a cost I'm willing to pay as a developer to see anki improve in a number of way. In particular, it'll allow to re-use some code from Anki in AnkiDroid, which will be a huge time win. But right now, there is little I can do.

**Comment by hugomarins** [comment]
Thanks Arthur. You're doing a lot, I really know that. By the way, how can we make donations to you? I can't find you in Patreon or Ko-fi anymore.

About gathering people to afford for this add-on, I am willing to participate, even though affording alone, by myself, maybe would be beyond my capacity (brazilians currency doesn't help!). 

Anyway, tell me how to donate to you, and thanks for all your efforts!

**Comment by Arthur-Milchior** [comment]
Thank you for inquiring about donation. It's mostly a tax nightmare to declare , and now that I 've got a job at Google, dealing with the few donation I used to get is mostly a tax nightmare than an income.

I miss this add-on myself so hope to eventually have time to recreate this add-on

**Comment by hugomarins** [comment]
Congratulations for your new job in Google! I'm sure you'll be very successful in you career!
